stages:
  - build
  - package

variables:
  NODE_VERSION: 12.16.3

build:
  stage: build
  image: node:$NODE_VERSION
  script:
    - yarn
    - yarn build
    - yarn --prod
  tags:
    - docker
  artifacts:
    expire_in: 1 day
    paths:
    - .

package:
  stage: package
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  variables:
    GIT_STRATEGY: none
  script:
    - sed -i 's/node:12/'node:$NODE_VERSION'/g' $CI_PROJECT_DIR/Dockerfile
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - EXTRA_ARGS=""
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG $EXTRA_ARGS
  tags:
    - docker
  dependencies:
    - build
